package br.furb.corba.DatabaseStorage;


/**
* DatabaseStorage/_DatabaseStorageStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl
* Domingo, 22 de Maio de 2016 09h52min06s BRT
*/

public class _DatabaseStorageStub extends org.omg.CORBA.portable.ObjectImpl implements DatabaseStorage
{

  public org.omg.CORBA.Object[] listMusicsByName (String name)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listMusicsByName", true);
                $out.write_string (name);
                $in = _invoke ($out);
                org.omg.CORBA.Object $result[] = ObjectArrayHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listMusicsByName (name        );
            } finally {
                _releaseReply ($in);
            }
  } // listMusicsByName

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DatabaseStorage/DatabaseStorage:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _DatabaseStorageStub
