package br.furb.corba.DatabaseStorage;


/**
* DatabaseStorage/DatabaseStorageOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl
* Domingo, 22 de Maio de 2016 09h52min06s BRT
*/

public interface DatabaseStorageOperations 
{
  org.omg.CORBA.Object[] listMusicsByName (String name);
} // interface DatabaseStorageOperations
