package br.furb.corba.DatabaseStorage;


/**
* DatabaseStorage/java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl
* Domingo, 22 de Maio de 2016 09h52min06s BRT
*/

public interface DatabaseStorage extends DatabaseStorageOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DatabaseStorage
