package br.furb.corba.DatabaseStorage;

/**
* DatabaseStorage/DatabaseStorageHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl
* Domingo, 22 de Maio de 2016 09h52min06s BRT
*/

public final class DatabaseStorageHolder implements org.omg.CORBA.portable.Streamable
{
  public DatabaseStorage value = null;

  public DatabaseStorageHolder ()
  {
  }

  public DatabaseStorageHolder (DatabaseStorage initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DatabaseStorageHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DatabaseStorageHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DatabaseStorageHelper.type ();
  }

}
