package br.furb.corba.DatabaseStorage;


/**
* DatabaseStorage/ObjectArrayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl
* Domingo, 22 de Maio de 2016 09h52min06s BRT
*/

public final class ObjectArrayHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.CORBA.Object value[] = null;

  public ObjectArrayHolder ()
  {
  }

  public ObjectArrayHolder (org.omg.CORBA.Object[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ObjectArrayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ObjectArrayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ObjectArrayHelper.type ();
  }

}
