package br.furb.corba.FileStorage;
/**
* FileStorage/FileStorageHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl
* Quarta-feira, 1 de Junho de 2016 12h08min02s BRT
*/

public final class FileStorageHolder implements org.omg.CORBA.portable.Streamable
{
  public FileStorage value = null;

  public FileStorageHolder ()
  {
  }

  public FileStorageHolder (FileStorage initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FileStorageHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FileStorageHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FileStorageHelper.type ();
  }

}
