package br.furb.corba.FileStorage;

/**
* FileStorage/java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl
* Quarta-feira, 1 de Junho de 2016 12h08min02s BRT
*/

public interface FileStorage extends FileStorageOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FileStorage
