package br.furb.corba.FileStorage;


/**
* FileStorage/java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl
* Domingo, 29 de Maio de 2016 14h44min50s BRT
*/

public interface FileStorage extends FileStorageOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FileStorage
