package br.furb.corba.FileStorage;


/**
* FileStorage/FileStorageOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl
* Domingo, 29 de Maio de 2016 14h44min50s BRT
*/

public interface FileStorageOperations 
{
  String getMusicsInFolder (String path);
  double getMusicSize (String path);
} // interface FileStorageOperations
