package br.furb.corba.FileStorage;

import java.rmi.RemoteException;

/**
* FileStorage/FileStoragePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl
* Quarta-feira, 1 de Junho de 2016 12h08min02s BRT
*/

public abstract class FileStoragePOA extends org.omg.PortableServer.Servant
 implements FileStorageOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getMusicsInFolder", new java.lang.Integer (0));
    _methods.put ("getMusicSize", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // FileStorage/FileStorage/getMusicsInFolder
       {
         String path = in.read_string ();
         String $result = null;
         try {
			$result = this.getMusicsInFolder (path);
		} catch (RemoteException e) {
			e.printStackTrace();
		}
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // FileStorage/FileStorage/getMusicSize
       {
         String path = in.read_string ();
         double $result = (double)0;
         $result = this.getMusicSize (path);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:FileStorage/FileStorage:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FileStorage _this() 
  {
    return FileStorageHelper.narrow(
    super._this_object());
  }

  public FileStorage _this(org.omg.CORBA.ORB orb) 
  {
    return FileStorageHelper.narrow(
    super._this_object(orb));
  }


} // class FileStoragePOA
