package br.furb.corba.FileStorage;

import java.rmi.RemoteException;

/**
* FileStorage/FileStorageOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl
* Quarta-feira, 1 de Junho de 2016 12h08min02s BRT
*/

public interface FileStorageOperations 
{
  String getMusicsInFolder (String path) throws RemoteException;
  double getMusicSize (String path);
} // interface FileStorageOperations
